### ISSUE TITLE
Factions are goin when onlinemode is true

### ISSUE THREAD

**Issue by luckymine** [MassiveCraft/MassiveCore#207]
Hello.
Iam i need of some help with factions/mcore

What is my problem.
Iam having a server that i made in offline mode so i can use cracked account for testing bugs on plugins on my server,same with some friends Now what happend i made the server all is working well i have the latest versions of spigot van plugins that work with 1.8 also the latest factions and mcore/update for 1.8

My problem is that when i was finished with my server en some players tested it for some days and made factions and claimed land [no errors] of any kind i decited to take my server to the online mode in server.settings.online-mode true.

Now i started the server and whent playing But what happend all the factions are goin and players canot go to there homes or do /f claim,they all needed to make a new faction and claim again so it seems.

However when iam stopping the server and go into server.settings and set online-mode False
All the factions are back and players can play claim go to there homes.

So before i set my server online for other players i like to know what iam doing wrong.

Why are the factions goin when iam setting online-mode true.

If someone can help me with this plz let me know

**Comment by oloflarsson** [comment]
The player ids are different in online mode and offline mode.
Simply put the server believes the players to be different players than before.
The factions are still there, it's just not recognizing the players as members of them anymore.

To my knowledge there is no good way to fix this.
The solution is to reset your faction database.

**Comment by luckymine** [comment]
Oke then Thanks
