### ISSUE TITLE
factions_uconf@default will not generate on first time server start up

### ISSUE THREAD

**Issue by killyouslow** [MassiveCraft/MassiveCore#213]
Why isnt the lastest version of mcore and factions creating a factions_uconf@default file in the MStore folder @ server startup??? We all literally NEED it to disable factions perworld without jerking around with the mconf settings i.e Worldsnopowerloss etc

seriously without factions_uconf@default mcore LITERALLY has NO multiworld support !!!!

someone please help me / answer this post

PM me on bukkit or skype me @ kill_you_slow ty soo much for reading :)

**Comment by oloflarsson** [comment]
The factions_uconf has been removed. Jerking around with the perworld options in factions_mconf is the way to go. You can also run sepparate servers behind bungeecord if you need further sepparation.

**Comment by killyouslow** [comment]
Well your plugin official sucks now, which is why ill be purchasing FactionsUUID premium from drtshock, make your plugins user friendly you dick!

**Comment by oloflarsson** [comment]
So does Drtshocks plugin have universe support? :smile_cat:

**Comment by killyouslow** [comment]
actually dirtshock's plugin comes with everything your plugin has without the use of mcore, and your plugin doesnt have universe support because i cant disable aspects per multiverse or universe because mcore doesnt work, fix your plugin

**Comment by oloflarsson** [comment]
It sounds to me like you are a bit missinformed. Drtshocks fork is based of an old version of Factions. As such it is missing many features. It does not contain universe support.
