### ISSUE TITLE
Getting this error?

### ISSUE THREAD

**Issue by Vidsify** [MassiveCraft/MassiveCore#225]
Title says it all

http://pastebin.com/zS2MhiDQ
http://pastebin.com/tKAcUVHi

Thanks

**Comment by ulumulu1510** [comment]
This error file is not pointing at MassiveCore  but at ModReq. The Part of massivecore is just the enable message, which appears every startup.

Please go post this error log at the support place for Modreq.

**Comment by Vidsify** [comment]
@ulumulu1510 Oh ok thank you

**Comment by ulumulu1510** [comment]
@Vidsify 
I believe, you can close your issue yourself. :) Thanks.
