### ISSUE TITLE
Not really an issue just a question

### ISSUE THREAD

**Issue by Moocow9m** [MassiveCraft/MassiveCore#226]
What is the point to this Core plugin(as in what does it do that the others need)?

**Comment by magnusulf** [comment]
A lot of things. There is utils for really many things the other plugins need.
Commands, database, configuration, titles, and many more utilities. The benefit of this is that the code only has to be updated once and not several places.
Also performance won't be noticeable degraded by MassiveCore. Having several plugins doesn't hurt you, so having a little Brady isn't bad.

**Comment by Moocow9m** [comment]
Thanks
