### ISSUE TITLE
Minecraft backend fetches need a timeout.

### ISSUE THREAD

**Issue by romanalexander** [MassiveCraft/MassiveCore#228]
https://github.com/MassiveCraft/MassiveCore/blob/6b09cb600da7d4c9a74785aca1d968f5ffd4fd4f/src/com/massivecraft/massivecore/fetcher/FetcherByNameSingle.java#L128

SocketInputStream is not guaranteed to complete in a timely manner. All mojang API calls need to be updated. No, "setConnectionTimeout" [will not help here](http://stackoverflow.com/a/11790633/2002323).

**Comment by oloflarsson** [comment]
This source code is not used at the moment. If you need it updated in some certain way feel free to provide a pull request.
