### ISSUE TITLE
Server lag Timings

### ISSUE THREAD

**Issue by Kedarin** [MassiveCraft/MassiveCore#230]
Hi,
I don't understand why Massive core get : 
     0.00%	 958.63%	  0.48 s	   479.31 ms	 0.0	       0.0k	    Task: MassiveCore$7(Single)
My timings : http://timings.aikar.co/?url=11501230

Server version : version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
Massivecore version : 2.7.5
Factions version : 2.7.5

Thank you,

**Comment by magnusulf** [comment]
Can you say anything about your server specifications?

**Comment by Kedarin** [comment]
That is to say? This is a PvP / Factions

**Comment by magnusulf** [comment]
Computer specs. Processor. Harddrive. Memory etc.

**Comment by Kedarin** [comment]
Linux,
Java 7 
Dedicated server  : http://www.soyoustart.com/fr/cpu/
I have the E3-SAT-2 server

**Comment by magnusulf** [comment]
Maybe you could just post the specs here instead of linking to a website on french.

**Comment by Kedarin** [comment]
processor : Intel Xeon E3 1225v2
Cores : 4 c/ 4 t
Freq : 3.2 GHz+
RAM : 32GB
DISK : 2 x 2 TB SATA

**Comment by Noahyup** [comment]
Lag-and not in haste based on factions http://prntscr.com/7s4eag
See authme!
