### ISSUE TITLE
Random cmd error with massivecore info

### ISSUE THREAD

**Issue by jewelsy15** [MassiveCraft/MassiveCore#231]
i've been making a prison server with factions on but i been seeing a random error saying "this person isn't on the server at the moment" i looked in the log and it had the same text that starting up massive core have. i can also show proof with a image and text: [0;31;1mThat player isn't on the server at the moment.[m
http://bukkit.org/attachments/screenshot-png.24419/

**Comment by ulumulu1510** [comment]
Can you please point out the full log? And please pastebin it, it makes reading a lot esier on a mobile device.

**Comment by jewelsy15** [comment]
Here you go mate: http://pastebin.com/PjkJafw2

**Comment by oloflarsson** [comment]
The phrase "That player isn't on the server at the moment" does not come from any plugin I made.
