### ISSUE TITLE
Problem with Java 7: Double#isFinite() does not exist

### ISSUE THREAD

**Issue by NLthijs48** [MassiveCraft/MassiveCore#234]
Factions is spitting out [this](http://pastebin.com/Tg949Adp) error a lot. The problem is that the Double#isFinite() method is not available in [Java 7](http://docs.oracle.com/javase/7/docs/api/java/lang/Double.html), but is in [Java 8](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#isFinite-double-). So I suspect that Java 8 is used to make testbuilds.

**Comment by magnusulf** [comment]
When the source code was originally written nobody thought that it was only available in Java 8+
The most recent version of MassiveCore has addressed this issue, however it has not been published to Spigot or BukkitDev yet.
Solutions to this problem could be:
* Install Java 8. If you manage the computer, this is probably the easiest (suggested)
* Wait for the next version of MassiveCore and Factions.
* Compile the latest version of MassiveCore and Factions yourself. You can get the source code here on GitHub (perhaps difficult)
* Temporarily downgrade to MassiveCore and Factions 2.7.5 (not suggested)

**Comment by NLthijs48** [comment]
Thanks for your answer, I will probably be updating to Java 8 soon. But if that is not soon enough then I'll try to compile the sources myself.
