### ISSUE TITLE
Please Help Me ASAP

### ISSUE THREAD

**Issue by LouisSpectrum** [MassiveCraft/MassiveCore#236]
Hi, Im Launching A Server Tomorrow And I Have Been Given This Bug That I Dont Know How To Fix!
Here Is The Problem Picture- http://prntscr.com/8n8hws

**Comment by ulumulu1510** [comment]
This is a Factions issue. Read the documentation here https://www.massivecraft.com/factions-configure and pay close attention to line 305 - 330 in the chapter of Factions config.
