### ISSUE TITLE
Some sort of exception.

### ISSUE THREAD

**Issue by OtakuHalo** [MassiveCraft/MassiveCore#238]
Hello there.

I'm Halo, the co-owner of a new server, and it appears we're having some issues. Here is a log file: https://www.dropbox.com/s/rr9q2qxu2361o4l/latest.log?dl=0

It appears MassiveCore is causing some sort of repeating error, and is spamming the console. We'd like a way to either disable the output of these errors, or a fix for what is causing them.

Thank you for your time, and thank you in advance for any help that can be provided,
~Halo and Jaffa, Stab Studios

**Comment by ulumulu1510** [comment]
Are you not running a spigot server perhaps? I can see from the log that this is a 1.8 server, so it should be a spigot one. For the 1.8 Itemstacks we use a spigot method, given that only spgito has updated to 1.8 and beyond. So could you please elaborate what server software you are using including its version and the version of Massivecore you are using?

**Comment by OtakuHalo** [comment]
It seems we were running bukkit, the latest version, gotten from the spigot site. We're also running the latest version of MassiveCore, I believe. Jaffa is working on fixing it, working on the assumption that switching over to Spigot will fix this issue. Is this the correct course of action?

**Comment by ulumulu1510** [comment]
Yes. We ourself run the latest version of spigot and compile against them.

I know, the build-tools spit out a craftbukkit/bukkit and spigot jar, but it is important that you run the spigot one since the newer API methods are only implemented there (like the itemMeta.spigot() which is causing your errors on the console)

**Comment by OtakuHalo** [comment]
Right, thanks. We fixed the problem. Jaffa was flipping out over the fact that the solution was so simple (Aside from the convoluted spigot installation. They need to make that simpler, but that's a topic for another place.) and we didn't think of it until you pointed it out. Ah well, thank you for your help, we really appreciate it.

~Halo and Jaffa, Stab Studios
