### ISSUE TITLE
Resets health to 10 hearts on join when other plugins set maxhealth

### ISSUE THREAD

**Issue by RoboMWM** [MassiveCraft/MassiveCore#241]
Plugins like [this](https://www.spigotmc.org/resources/customhealth.8235/) work properly if and only if MassiveCore is not installed. It seems that MassiveCore is resetting player health back to 20 if the player disconnected with over 20 health. I tried making the plugin load before and after MassiveCore with no success.

**Comment by oloflarsson** [comment]
So I took a look at the source code for https://www.spigotmc.org/resources/customhealth.8235/

That plugin sets the player health on login and respawn to it's own config value `default_max_health`. Are you sure you simply have not misinterpreted what that plugin does?

**Comment by RoboMWM** [comment]
That's what it did initially, but he changed this in the update, and on reconnect properly restores health from disconnect

**Comment by RoboMWM** [comment]
Just took a peek at the code as well, and it's only doing setMaxHealth, not setting health. So MassiveCore must be setting player health to 20 if health > 20?

**Comment by oloflarsson** [comment]
I have fixed this in a resent commit.

**Comment by Pfctink** [comment]
Where is this fix?

**Comment by magnusulf** [comment]
d3c025b288f69d5f48dd62d090bcfa6feee1cb7d

**Comment by Pfctink** [comment]
How can I apply this fix to the most recent patch for Massive Core?

**Comment by RoboMWM** [comment]
You'll probably need to build it yourself, which is a pain since this has been de-mavenized for not-very-good reasons >_>

**Comment by MarkehMe** [comment]
You don't need to use maven to compile it and it's quite easy to reorganise your maven configuration to work with MassiveCraft projects! :smiley:

**Comment by Pfctink** [comment]
Would like to see it actually compiled. If possible.

**Comment by magnusulf** [comment]
@Pfctink, we don't go around and compile it to everyone who asks for it. We choose to spend our time on something else. But you can clone it and compile it yourself. If you choose to do so, remember to also compile and use the latest version of our other plugins, otherwise they won't run.

@RoboMWM a bug tracker exists to help people and fix bugs. Not to express your own irrelevant subjective opinion.
