### ISSUE TITLE
Massive core, disable chat

### ISSUE THREAD

**Issue by LudusMC** [MassiveCraft/MassiveCore#245]
Greetings,

I've recently downloaded your plugin MassiveCore to be able to run MassiveTickets and MassiveBooks and i have to say, i'm very impressed with all of them. Great job and keep up the fantastic work!

I have a minor problem though... I'm using the plugin HeroChat for my chat related needs.
The moment i installed MassiveCore, when a player says something in chat, it gets repeated by your plugin...

Example: http://imgur.com/T3Np2Wd

Is there a way to disable the chat feature of MassiveCore?

Thanks for your time,
Regards

**Comment by ulumulu1510** [comment]
Thank you for your feedback.

To help you, we always need your Plugin and Spigot Version. 

I am not completly sure, but this time I might be able to do without:
There is a configuration option called "usingRecipientChatEvent", have you tried turning this one off?

We have noted in the past that the Plugin HeroChat causes this issue at times, so please report back your Version numbers and your configuration of the MassiveCore MConf.

**Comment by LudusMC** [comment]
----Spigot Version----
CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

----Plugin Version-----
v2.8.5

At first i couldn't find the mstore directory, so, i couldn't find the massivecore_mconf directory. Then i stumbled upon it a few minutes ago... i set the usingRecipientChatEvent to false and surprisingly it worked!

Thank you so much for your help, keep up the amazing job and have a fantastic day,
Regards
