### ISSUE TITLE
 Error: Raw data was null. Is the file completely empty?

### ISSUE THREAD

**Issue by MrPotatu** [MassiveCraft/MassiveCore#247]
Hey, I am getting this error every time I start the server, and it keeps comming up as the server is running. What can I do solve this?

http://pastebin.com/159vwAXY

**Comment by magnusulf** [comment]
This is a database error. A file is corrupted, perhaps by a manual edit, perhaps by a hard drive failure, perhaps by the OS or some other software mistake, or perhaps by something else. Simply delete the files.

**Comment by MrPotatu** [comment]
Thanks for the response. But when I remove these files, other ones shows up...
