### ISSUE TITLE
Error produced whenever files are edited

### ISSUE THREAD

**Issue by Flashera** [MassiveCraft/MassiveCore#251]
Whenever files are edited (at least on my server) it produces this error:

[20:22:36] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;31;1mDatabase could not load entity. You edited a file manually and made wrong JSON?[m
[20:22:36] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;36;1mEntity: [0;35;1mMessage[m
[20:22:36] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;36;1mCollection: [0;35;1machat_channels[m
[20:22:36] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;36;1mError: [0;35;1mRaw data was null. Is the file completely empty?[m

In the case of AbsentChat, I can edit channels and it works despite the error, but when I edit the instance.json it does not work upon edit.

This issue persists with Massivecore and Factions, so I don't think this is an AbsentChat issue, though I have notified the developer of that as well.

**Comment by magnusulf** [comment]
The file is completely empty. Either a disk error occurred or you made a mistake when editing the file. Simple remove it and let a new generate.

**Comment by Flashera** [comment]
This did not fix my issue, I tried this already.

**Comment by magnusulf** [comment]
Does the issue persist on both remote server and local test server. Does it persist when only having MassiveX plugins installed?
This error is usually caused by server owners handling files wrongly or by seldom io failures which cannot be avoided.

**Comment by Flashera** [comment]
Issues do not seem to persist on my local server so it may be the host. I will contact them,

**Comment by MarkehMe** [comment]
What OS and filesystem type is your host?

**Comment by Flashera** [comment]
I believe they use Linux Ubuntu and I'm guessing you are asking for their hard drive type which is SSD.

**Comment by SmallSansSerif** [comment]
Yes, I also saw this behavior on Ubuntu Linux with the released beta configs.

**Comment by MarkehMe** [comment]
I meant Filesystem type.. e.g, ext3, NTFS, HFS+, etc.

**Comment by Flashera** [comment]
Sorry for the long wait between my last response, I was busy. I have sent a ticket to my host and they said they use Ext4

**Comment by oloflarsson** [comment]
I am personally using Ext4 and I do not get this error. I doubt it has anything to do with the file system.

**Comment by oloflarsson** [comment]
Have you figured this out yet @Flashera?

**Comment by Flashera** [comment]
The issue seems to have ceased, my guess is that they may have had something wrong with their network or FTP servers.
