### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by sgyoutuber265** [MassiveCraft/MassiveCore#252]
It won't work. It just doesn't work for 1.9, if you know how to fix this please email me or skype me sgyoutuber265

**Comment by MarkehMe** [comment]
1.8.7 is in Beta and you will experience issues. Please provide actual error logs or something more helpful, because we really can't do anything with what you've told us :smile: 

If it is having serious effects on gameplay you should just downgrade and wait :wink:
