### ISSUE TITLE
MassiveCore Not loading on 1.9

### ISSUE THREAD

**Issue by pieceofchees** [MassiveCraft/MassiveCore#253]
Hello,
I recently upgraded from 1.8 to 1.9 but MassiveCore (and Factions) are not loading. There is no error. There is nothing at all in the log related to MassiveCore or Factions

( The Whole Log: http://pastebin.com/kFJ4Hakm, Ignore the citizens errors. )

**Comment by ulumulu1510** [comment]
When you download the MassiveCore plugin on spigot, you get a zip of all MassivePlugins. Did you unzip that properly? 

If so, did you try a test server with only MassiveCore and Factions installed?

If that doesn't work, screenshot your plugins folder and attach the picture to this issue.

**Comment by pieceofchees** [comment]
You are right xD, I'm so stupid. Recently all my .jar files turned into .rar files somehow so I didn't notice.
Thank you for your reply.
