### ISSUE TITLE
MassiveCore removing [World] prefix

### ISSUE THREAD

**Issue by jjacck1** [MassiveCraft/MassiveCore#254]
If I add MassiveCore to my server and reload, I get this:
<img width="489" alt="screen shot 2016-03-29 at 21 57 11" src="https://cloud.githubusercontent.com/assets/2822823/14138310/885a111a-f664-11e5-9458-27fbcba11caf.png">

The console looks like this:
<img width="354" alt="screen shot 2016-03-29 at 21 57 19" src="https://cloud.githubusercontent.com/assets/2822823/14138339/a3c92e72-f664-11e5-8e2d-352a7f813767.png">

[Test] in the console was the world prefix I wanted in the chat.

You can see that the world prefix is not following through onto the chat. I have tampered with the chat settings in the essentials and factions config's while having MassiveCore installed and cannot get the prefix to appear in chat. The only way that the prefix will show in the chat is by removing MassiveCore from the plugins, in which case I get this:
<img width="383" alt="screen shot 2016-03-30 at 10 04 15" src="https://cloud.githubusercontent.com/assets/2822823/14138425/2429428c-f665-11e5-9e7d-0e7b87bb2652.png">

Please ignore the [owner] prefix changing, that was due to tampering the essentials config.

How can I regain my prefix without removing MassiveCore? I need it for factions.

Thanks for your time,
Jack

**Comment by ulumulu1510** [comment]
It might have been uncarefull wording, but never ever reload your server. It breaks MassiveCore DB system and can potentially harm your server.

If another plugin handles your chat, turn "usingRecipientChatEvent" off in the MassiveCore Mconf and see whether this works out for you.

**Comment by jjacck1** [comment]
Perfect. Thanks!
