### ISSUE TITLE
MassiveCore InvalidPluginException

### ISSUE THREAD

**Issue by ChrisLane** [MassiveCraft/MassiveCore#262]
### Copied from a Thermos issue
https://github.com/CyberdyneCC/Thermos/issues/353
I'm not convinced that this is a MassiveCore issue since the plugin works on standard spigot 1.7.10 but I also am not really able to ague the opposite so feel free to post on that issue.

**Server Log:**
http://pastebin.com/q86AuDhG

**FML Log(s):**
http://pastebin.com/kPsAksQE

**Explanation of issue:**
MassiveCore fails to load on startup and produces the error seen in the server log.
Tested with vanilla 1.7.10 craftbukkit and the error was not produced.

This error occurs in MassiveCore 2.8.11 to 2.8.13 (latest at time of posting)

**How to recreate this issue:**
Server startup

**Plugins Installed:**
MassiveCore 2.8.11

**Thermos Version:**
Build 56

**Forge Version:**
1.7.10-1614

**Comment by MarkehMe** [comment]
If it worked on Spigot 1.7.10 then I would say its an issue with Forge. 

The error occurs where we call ```NmsItemStack.get().classCraftItemStack```: https://github.com/MassiveCraft/MassiveCore/blob/4c1907ba0737e5371ce2cf440fb5ef03ade76d25/src/com/massivecraft/massivecore/MassiveCore.java#L188

Still investigating this for you.

**Comment by MarkehMe** [comment]
Fixed 😄
