### ISSUE TITLE
Particles arn't showing up

### ISSUE THREAD

**Issue by TheHardestBunnyAlive** [MassiveCraft/MassiveCore#264]
My server is running spigot 1.10 and the latest version of massivecore and so is my plugin. I got the latest version of spigot and massivecore in the build path of my plugin. But the particles are not showing up in game when I try to turn them on. I get this error in my console.
![error](https://cloud.githubusercontent.com/assets/4650048/15987833/480adae6-3006-11e6-9974-0c3d4a5cd993.png)

**Comment by oloflarsson** [comment]
Fixed in this commit: https://github.com/MassiveCraft/MassiveCore/commit/1439eef15d536317172e18033a0757e795037beb
