### ISSUE TITLE
Mcore ( with Faction ) is not compatible with "Skript" plugin.

### ISSUE THREAD

**Issue by Beerus-Sama** [MassiveCraft/MassiveCore#266]
i'm sorry if i make mistake ( i don't speak english very well ) , and i'm sorry if i post this into the wrong category ( that's the firt time i do this ) 
I want to tell you that , your plugin massivecore ( and faction ) are not compatible with the plugin called " skript " ( the faction plugin can work , but skript can't ) here's the console error : http://pastebin.com/HsNe4uyF

**Comment by MarkehMe** [comment]
Please note that multicraft doesn't actually give you the entire log - you can see at the bottom it says ```[Multicraft] Skipped 54 lines due to rate limit (30/s)```. In the future, open the server log file and you can grab the full log from there 😁 

So the issue is probably an external issue with Skript (or the version of Skript you're using) try updating your Skript plugin first.

**Comment by ulumulu1510** [comment]
It is most definitely an issue with the script plugin.
It tries to access the method Rel#parse, but there is no such method present in our current code.

Either the reference outdated versions of Factions, or they don't use the java API properly. There is a method that allows you to get an enum constant from a String, but it''s name is Enum#valueOf (String string).

**Comment by Beerus-Sama** [comment]
[http://memesvault.com/wp-content/uploads/Wat-3d-Gif-12.png](url)

**Comment by Beerus-Sama** [comment]
> Please note that multicraft doesn't actually give you the entire log - you can see at the bottom it says [Multicraft] Skipped 54 lines due to rate limit (30/s). In the future, open the server log file and you can grab the full log from there :grin:

So the issue is probably an external issue with Skript (or the version of Skript you're using) try updating your Skript plugin first.

**Thanks for the reply , yes i know that there is a multicraft rate limit on the console , but i did not find where the logs files are , skript is up to date ! Thanks a lot for your quick response**

> It is most definitely an issue with the script plugin.
 It tries to access the method Rel#parse, but there is no such method present in our current code. 
Either the reference outdated versions of Factions, or they don't use the java API properly. There is a method that allows you to get an enum constant from a String, but it''s name is Enum#valueOf (String string).


**Thanks for the help , i hope that this ( i do not understand any thing :smile_cat:  , but i love u :heart: )
The important is that you give me an idea of what is the problem , and that will be useful for me !
So the problem is from skript ? I don't think they are active on their github , is there any way to modify the code for solving this ? ( I can pay , my server is like an investment for me )**

And sorry for my bad english ( And i want to ask you : Is my writing is good ? I'm french and i study a little english and that ticket is a way to improve my english :smiling_imp: )

**Comment by MarkehMe** [comment]
Your English is understandable. 

The Skript plugin must be updated to use the Factions API properly. Please reference this thread in any reports to the developer, and they should understand!
