### ISSUE TITLE
Fails to register listeners because class is missing/not existing yet.

### ISSUE THREAD

**Issue by Twonox** [MassiveCraft/MassiveCore#267]
`MassiveCore version: 2.8.19`
`Server version: PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest`

> http://hastebin.com/awocireyus.m

**Comment by ulumulu1510** [comment]
Could you give me the full server log please? I need to see when and under which circumstances this happened.

**Comment by Twonox** [comment]
http://hastebin.com/omixayumix.py

**Comment by oloflarsson** [comment]
OK, does the plugin work though?

**Comment by Twonox** [comment]
Yes

**Comment by ChrisLane** [comment]
So...we can close this? The plugin works fine, it just can't find the 1.8+ classes.
