### ISSUE TITLE
Thermos specific fix in the codebase?

### ISSUE THREAD

**Issue by ChrisLane** [MassiveCraft/MassiveCore#272]
Would a fix specifically for Thermos get pulled into the codebase?
I've created a small fix for #262 at https://github.com/ChrisLane/MassiveCore/commit/1dcae6782b1b9ba39f0ae627ba70da671ca78d34

Just wondering whether to make a pull request or not.

**Comment by MarkehMe** [comment]
Thanks for your help Chris! I have already implemented something similar in a fork, however I have not yet sorted out one last issue with our CommandSender not being set (I just honestly haven't had time lately)

**Comment by ChrisLane** [comment]
Isn't that something you fixed in the MassiveCoreForgeFixes plugin?

**Comment by MarkehMe** [comment]
It would be preferred to be fixed in MassiveCore with a less hacky method. I'll bring this up today and see if we can fast track it! 😄
