### ISSUE TITLE
Double chat

### ISSUE THREAD

**Issue by JumanjiCraft** [MassiveCraft/MassiveCore#274]
So I'm having an issue that seems to be popular with massivecore. I have a double chat showing in my server. 

Now, I can temporarily solve the issue by deleting the MassiveCore mcore.json file in the plugin folder, and manually reloading MassiveCore (via plugman, which causes an error). But I also followed other advice and edited the JSON file with ::

```json
{
  "serverid": "b3ff23bc-0952-4195-b370-a35dbc0c445b",
  "dburi": "default",
  "alias2uri": {
    "default": "flatfile",
    "flatfile": "flatfile://mstore",
    "usingRecipientChatEvent": "false",
    "mongodb": "mongodb://localhost:27017/mstore"
  }
}
```

However, I still experience double chat on the server after every server restart. 

Here's a list of plugins:

```
WorldBorder, Simple-Broadcast, PlugMan, ItemRestrict, WorldEdit, BukkitCompat, MassiveCore, Vault, Multiverse-Core, PermissionsEx, LogBlock, LightAPI, LWC, TreeAssist, WorldGuard, Commandspy, CustomHelp, ProtectionStones, ShinyItems, XRayDetector, Announcer, ScheduledCommands, iDisguise, Votifier, Herochat, Essentials, Jobs, Citizens, Towny, CreativeGates, ShopChest, SavageDeathChest, EnjinMinecraftPlugin, OnTime, PlayerPoints, ChestCommands, BossShop, GuiShopManager
```

And here's the bug in action. 

http://prntscr.com/c6vdbn

Thanks in advanced to any insight you guys/gals can share! <3

**Comment by MarkehMe** [comment]
_I've modified your original message for readability_

Hello! Thanks for all the information - this is something a lot of people don't do. For that, I owe you one. 🎉 

Can you share your ```factions_mconf/instance.json``` please?

**Comment by JumanjiCraft** [comment]
Well, I don't have factions, so I suppose I have to ask, where do you think I could find such a file? I do have towny.

**Comment by MarkehMe** [comment]
Ooops.. my apologies, I miss-read. 

If you disable **HeroChat** does the issue persist?

**Comment by JumanjiCraft** [comment]
All that information and you didn't read it? :P jk. :+1: 

No.

http://prntscr.com/c76au2

**Comment by MarkehMe** [comment]
Out of curiosity what happens when ```usingRecipientChatEvent``` is set to ```true```?

**Comment by JumanjiCraft** [comment]
One moment, and I'll try that.

**Comment by JumanjiCraft** [comment]
The issue persists. 

Issue
http://prntscr.com/c76fof


.json
http://prntscr.com/c76ftt

**Comment by JumanjiCraft** [comment]
I tried adding these to the json with no success:

...
"chatSetFormat": false,
...
"chatParseTags": false,

**Comment by JumanjiCraft** [comment]
The above attempt did not fix the issue.

**Comment by MarkehMe** [comment]
I'm honestly not sure but I believe it has something to do with HeroChat.

**Comment by JumanjiCraft** [comment]
I'll ask in the HeroChat help! Thanks for your time!

**Comment by MarkehMe** [comment]
Please update us with how you go!

**Comment by JumanjiCraft** [comment]
I will do

**Comment by JumanjiCraft** [comment]
The solution I came up with is to remove herochat and replace it with venturechat

**Comment by MarkehMe** [comment]
Great to here you have a solution. 

I've used VentureChat previously and it has worked really well!
