### ISSUE TITLE
MassiveCore issue on Cauldron

### ISSUE THREAD

**Issue by Plx0wn** [MassiveCraft/MassiveCore#275]
Hi guys! I found an issue on my Cauldron server! (cauldron-1.7.10-2.1403.1.54) 
I have MassiceCore and Factions version 2.8.20

Log:
[MassiveCore Issue.txt](https://github.com/MassiveCraft/MassiveCore/files/428200/MassiveCore.Issue.txt)

I love your plugins! Please correct this issue !

**Comment by MarkehMe** [comment]
Please wait for the next release of MassiveCore, Forge support was recently added.
