### ISSUE TITLE
NmsBoard not implemented

### ISSUE THREAD

**Issue by ChrisLane** [MassiveCraft/MassiveCore#276]
**MineCraft Version** 1.7.10
**Server Version** Thermos Build 58 (Forge 1614)
**MassiveCore Version** Built from this point: https://github.com/MassiveCraft/MassiveCore/tree/25f127e099fe8cb84830accc72b0e887682c4870
**Factions Version** 2.8.20

**Server Log** http://paste2.org/HhJLcZk9

An error is created when a player leaves the game.
An error is created when the plugin disables.

**Comment by MarkehMe** [comment]
Thanks for reporting! This is a known issue with ```NmsBoard``` in a Forge environment, however it is not game breaking. 

We'll keep this thread updated with improvements as we go.

**Comment by MarkehMe** [comment]
@ChrisLane perhaps you can help me out? 

I've been working on getting more of the nms classes to work: https://github.com/MarkehMe/MassiveCore/commit/34804fb48597e6d4deb23b3be2ea6461f05be81b

I can't seem to find the ```PlayerConnection``` class and a field for it (```playerConnection ```): 
* https://github.com/MarkehMe/MassiveCore/commit/34804fb48597e6d4deb23b3be2ea6461f05be81b#diff-c88726c964bb073ec6d0f719a45764b1R169 
* https://github.com/MarkehMe/MassiveCore/commit/34804fb48597e6d4deb23b3be2ea6461f05be81b#diff-c88726c964bb073ec6d0f719a45764b1R179

Perhaps PlayerConnection was removed? I've been using [this](http://takahikokawasaki.github.io/minecraft-resources/javadoc/forge/1.8-11.14.1.1320/allclasses-noframe.html) as a guide.

**Comment by oloflarsson** [comment]
I'm afraid I'll now close this issue. Thermos is abandoned by it's authors and only ~3% of servers run it (https://bstats.org/global/bukkit). That does not mean I'm agains supporting Thermos. Feel free to code a pull request adding support at any time.
