### ISSUE TITLE
MassiveCore Causing Chat To Duplicate

### ISSUE THREAD

**Issue by logicalPolaris** [MassiveCraft/MassiveCore#277]
I'm using a plugin called PerWorldServer, and when it is enabled, MassiveCore duplicates the chat messages sent by it. The only thing that fixed it was setting recipientChatEventEnabled to false, but that causes all Factions tags to stop working.

Is there any simple fix for this, or is it an issue that the developer for PerWorldServer needs to fix?

Thank you!

**Comment by MarkehMe** [comment]
Do you use a chat management plugin?
