### ISSUE TITLE
MassiveCombat error in logs

### ISSUE THREAD

**Issue by PhanaticD** [MassiveCraft/MassiveCore#278]
http://pastebin.com/y3PevMrg

I have scoreboardExtraCompatibility true

**Comment by MarkehMe** [comment]
Please provide your server version and type, and any other information about your server you could provide.

**Comment by PhanaticD** [comment]
uhmm its prison server running paperspigot for 1.10.2, two plugins I use that modify scoreboards other than massivecombat would be 

CommandHelper which I use for a script for the side scoreboard: https://gyazo.com/4a99c5c0bd6b80dda602281df01b8667 

NameTagEdit for the titles above heads and in tab list: https://www.spigotmc.org/resources/nametagedit.3836/  https://gyazo.com/cc9f7c1641844ca4c32504002a4fceef https://gyazo.com/53973d196fe1c06ee89baa003d156a9a

**Comment by oloflarsson** [comment]
Can you please try on a local server with MassiveCombat only.
Then add CommandHelper and try again and see if the issue occurs. 
Then add NameTagEdit and try again and see if the issue occurs.
This way we can figure out which plugin is incompatible.

**Comment by ulumulu1510** [comment]
Closed because lack of response and testability.
