### ISSUE TITLE
Cannot edit apple cooldowns

### ISSUE THREAD

**Issue by PhanaticD** [MassiveCraft/MassiveCore#279]
> mcc gappleCooldownsMillis 0
> [05:11:38 INFO]: The sub command gappleCooldownsMillis couldn't be found.
> [05:11:38 INFO]: /mcc gappleCooldownMillis [set=show]
> [05:11:38 INFO]: Use /mcc to see all commands.

**Comment by oloflarsson** [comment]
It looks like you are using the command correctly. Are there any errors in the console earlier on, especially at server startup?

**Comment by PhanaticD** [comment]
not that I noticed, I ended up just editing the file directly

**Comment by ulumulu1510** [comment]
Closed for being inactive too long.
