### ISSUE TITLE
Massive Core too big

### ISSUE THREAD

**Issue by KKaGaming** [MassiveCraft/MassiveCore#280]
the file is too big my plugin jars can only go too 2mb, and Massive Core is 2.9mb anyway i can get it to a zip and its all split up, please help me and thank you :)

**Comment by SirFaizdat** [comment]
I don't think anything can be done about the file size. 

Perhaps you can contact your hosting provider to see if there is a way to upload the file. Some hosting companies allow you to access FTP via an online interface, and the online interface sometimes lets you upload archives (i.e. zips) that will be decompressed for you.

**Comment by KKaGaming** [comment]
ok ty and ty for the quick reply :)

**Comment by KKaGaming** [comment]
do you now of any good minecraft server hosts that are at a cheap price

**Comment by ulumulu1510** [comment]
This is not a MassiveCore issue anymore, so I'll close this issue.
