### ISSUE TITLE
Configurable - Don't reset exp and Levels to 0 on false "flagKeepXp"

### ISSUE THREAD

**Issue by PhanaticD** [MassiveCraft/MassiveCore#281]
I am assuming this section of the config is interfering with essentials.keepxp permission node

```
  "flagKeepXp": {
    "name": "XP",
    "description": "<i>Keep your XP on death.",
    "worldsTrue": {
      "standard": false,
      "exceptions": []
    },
    "worldsFalse": {
      "standard": false,
      "exceptions": []
    }
  },
```

Is there any specific configuration that would allow me to use the essentials feature? because right now it is blocking anyone from keeping XP on death

**Comment by ulumulu1510** [comment]
As this flag is configured currently,  in now world poeple keep their xp ( --> worldsTrue). I would suggest you to try setting standard to true on worldsTrue and let essentials override it. If they don't, they listen at a too high priority.

` "flagKeepXp": {
    "name": "XP",
    "description": "<i>Keep your XP on death.",
    "worldsTrue": {
      "standard": **true**,
      "exceptions": []
    },
    "worldsFalse": {
      "standard": false,
      "exceptions": []
    }
  },`

**Comment by PhanaticD** [comment]
if I do that "mcc flagKeepXp worldsTrue standard true"

no one keeps XP even with the permission from essentials

**Comment by ulumulu1510** [comment]
After further investigation in the code, there is no configuration possible since we manually set exp and levels to 0 if players don't keep their exp. This way, it doesn't matter whether or not essentials allows people to keep their exp.

I will mark this as a feature request.

**Comment by oloflarsson** [comment]
I have now fixed this issue. The fix will be part of next release.
