### ISSUE TITLE
Factions worldsClaimingEnabled

### ISSUE THREAD

**Issue by nuggs13** [MassiveCraft/MassiveCore#287]
Getting errors setting up worldsClaimingEnabled. I have tried a few alterative settings but no luck. Am i just not setting it up correctly, or is there an issue?

Using spigot 1.11.2 and  mcore 2.9.0     

https://www.dropbox.com/s/n9y6c369mytg8zu/facterr.png?dl=0

**Comment by ulumulu1510** [comment]
Please state your versions of:
* Factions
* MassiveCore
* Spigot

Describe detailed:
* What you did
* What you expected to happen
* What actually happened.

Also, add screenshots/pastebins of any errors you have in console. Please refrain from uploading them to dropbox, as I do not want to download anything I do not trust.

**Comment by ulumulu1510** [comment]
Also, please post this on the correct repository, this is the MassiveCore Rep. Post your Factions issue here:
https://github.com/MassiveCraft/Factions/issues and include the points above.
