### ISSUE TITLE
Certain blocks drop as if using silk touch

### ISSUE THREAD

**Issue by GEONEgames** [MassiveCraft/MassiveCore#288]
When broken, certain blocks (such as glowstone, bookcases, and cobwebs) drop as if they were broken with silk touch despite this not being the case. This only happens with Massive Core enabled, and I see no option or config to disable it. This makes it impossible to get glowstone dust for potions aside from killing witches.

Spigot for MC 1.11.2
MassiveCore 2.9.0
Java 8

**Comment by GEONEgames** [comment]
Never mind. It was the dropSelfMaterials in vampire_uconfig@default.

**Comment by MarkehMe** [comment]
Happy to hear you found a resolution :)
