### ISSUE TITLE
Bug - Configuration files not automaticly being reloaded when using MongoDB

### ISSUE THREAD

**Issue by MrDienns** [MassiveCraft/MassiveCore#290]
Hi,

The title should describe the global issue; configuration files are not automaticly reloaded by the core when using MongoDB. I tried using flatfile, and it works perfectly fine that way. Only MongoDB seems to cause this issue.

Using the latest (2.10.0) version.

Best regard

In case you didn't read it yet, apology for my last issue.

**Comment by Dienns** [comment]
bump

**Comment by ulumulu1510** [comment]
I will tag @oloflarsson at this, since I am not too well versed with mongodb yet.

**Comment by MrDienns** [comment]
I don't feel like being a typical annoying bug reporter, but it's been almost 3 weeks since my issue was created...

**Comment by ulumulu1510** [comment]
I hear you, @MrDienns. You are one of the more polite bug reporters we have actually, but I can't help you with your issue sadly.

From what I know (I'm not the sys-admin), we use MongoDB on our server as well and I am pretty sure that configuration files are automatically reloaded. 

I will tag @oloflarsson yet again, which is the only help I can provide.

**Comment by MarkehMe** [comment]
Hey @MrDienns - can you confirm this is still an issue? 

It's very hard to fix the issue if we cannot replicate it. Could you possibly add me on Skype (markehme) so we can discuss this?

**Comment by MarkehMe** [comment]
I have found the issue to be a documentation issue. 

The `_mtime`  variable is not automatically updated by MongoDB so must either be deleted or put to a larger-that-now integer. This should be added to the documentation.

**Comment by oloflarsson** [comment]
Yes, thank you @MarkehMe. The `_mtime` field must be manually modified since that is what the poller looks at for changes.
