### ISSUE TITLE
Feature request: log coloration

### ISSUE THREAD

**Issue by SlimeDog** [MassiveCraft/MassiveCore#292]
Please introduce a configuration option to disable formatting codes in log entries. I prefer plain text, no colors or etc. Make the default whatever you feel is most requested, but please give me the option.

**Comment by ulumulu1510** [comment]
This feature has been added in the version 2.13, thank you for your input:

https://github.com/MassiveCraft/MassiveCore/commit/d74690ec7c7e2054f64ebca1963ff862c39d714a
