### ISSUE TITLE
Select specific MongoDB entries

### ISSUE THREAD

**Issue by MrDienns** [MassiveCraft/MassiveCore#293]
Hi,

First of all, I know this isn't the way of asking questions like this, but MassiveCraft's Core has no documentation what so ever. No developer guide, and people in SpigotMC are not familiar with using the MassiveCraft Core either, so I hope I can get an answer this way.

I have a MongoDB collection for players. Simply a player registration.
I have another table that contains multiple documents for each player. Let's use this example for now:

One player can have multiple inventories. The player documents are created in the "player" collection, and the inventories are created in the "inventory" collection. Let's say one player can have 5 inventories. The inventory document has a UUID that indicates the owner, and ofcourse it also has a unique ID for the document itself.

I wish to create an array that contains all inventories of one player.

Right now I made it happen by simply selecting all documents & checking the owner UUID to see if it's theirs, which is obviously extremely inefficiënt & wrong in so many ways. I wish to improve this by simply using something like a where statement using the MassiveCraft Core (I'm an SQL guy).

Again, I know this isn't the way of solving these kind of issues, but I must really get this question answered and I don't see any other way of doing so, since we don't have any documentation on this project.

Really hope someone can help me with this

Thanks

**Comment by MarkehMe** [comment]
Hi @MrDienns 

This sounds like a really frustrating time for you and I _completely_ understand. MassiveCore isn't incredibly documented as its intention is to be used by MassiveCraft developers, however I'm sure things like this could be explained for hobbyist as well! 

I'm not 100% sure what you mean here though. Are you using MassiveCore and MStore for your own plugin? (thats awesome if you are - MassiveCore its a great library)

**Comment by MrDienns** [comment]
Yes, I am using the MassiveCraft core, the MStore and everything with it. MassiveCore is indeed a grewt way to make lots of custom plugins quickly, I love it.

Is the question itself clear? I gave an example above that should clearify it. If not, let me know.

**Comment by MarkehMe** [comment]
MassiveCore has an ORM-like setup built into it called [Entity](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/store/Entity.java) and in your case there is a predefined abstract model [SenderEntity](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/store/SenderEntity.java). I'm also assuming you configure MassiveCore to use MongoDB, these models will save right into MongoDB.

On top of this, MassiveCore automatically adds adapters for [so many objects](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/adapter/), and again in your case, [Inventory](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/adapter/AdapterInventory.java).

So you can go ahead and create your player class:

**SomePlayer.java**
```java
public class SomePlayer extends SenderEntity<SomePlayer> 
{
	// Store just one ...
	private Inventory inventory = null;

	// ... or many.
	private Map<String, Inventory> inventories = HashMap<String, Inventory>();

	// Examples for single inventory:

	public Optional<Inventory> getInventory()
	{
		Optional.of(this.inventory);
	}
	
	public void setInventory(Inventory inventory)
	{
		this.inventory = inventory;
	}
	
	public void clearInventory() 
	{
		this.inventory = null;
	}
	
	// Examples for multiple inventories:

	public void setInventory(String id, Inventory inventory)
	{
		this.inventories.put(id, inventory);
	}
	
	public Optional<Inventory> getInventory(String id)
	{
		return(this.inventories.get(id));
	}

	public Optional<Inventory>clearInventory(String id)
	{
		return(this.inventories.remove(id));
	}



}
```

I don't think you really need to do anything else with the Inventory object @magnusulf or @ulumulu1510  can probably confirm this for me _(I have been out of dev. with MassiveCraft for a while - I've been concentrating on personal projects, work, and my health - need to get back into it!)_

Now that you have extended the **Entity** class you need to extend the **Coll** class. We could use [Coll](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/store/Coll.java), but in this case MassiveCore has [SenderColl](https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/store/SenderColl.java) built in that you can extend. 

So you would create SomePlayerColl and do something similar to what is [here](https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/MPlayerColl.java).

**SomePlayerColl.java**
```java
public class SomePlayerColl extends SenderColl<SomePlayer>
{

	private static SomePlayerColl instance = new SomePlayerColl();
	public static SomePlayerColl get() { return instance; }

	// .. blah
}
```

You need init your Coll with `SomePlayerColl.get().setActive(true);` before using it (thats what `Factions.get().isDatabaseInitialized()` is checking for, but Factions also executes this onEnable). I dont' think you even need to override anything (except onTick - for stack traceability)


SO now with this, you should be able to just:
```
// .. player is logging in 
SomePlayer you = SomePlayerColl.get().get(id);
if (you.getInventory().isPresent())
{
	// .. apply that inventory to the player
}

// .. multiple worlds
World world = ..;
String worldId = world.getId();

if (you.getInventory(worldId).isPresent())
{
	Inventory applyThis = you.getInventory(worldId).get();
}
```

If you're doing something funky (like per world) you could put inventory into a Map.

Does this make sense?

**Comment by MrDienns** [comment]
Yes, this is a very clear example, however;

I you carefully read the example again, I stated thst one player will be given the ability to seitch between *multiple* inventories. The player can then simply choose from a ChestGui which one to select

I need to select mutliple documents in MongoDB from a certain player, probably using the player UUID.

Right now I simply select all, and loop through to determine which ones I need. This is obviously very poor in efficiency.

Do you have a solution for that?

**Comment by MarkehMe** [comment]
So yep, I did throw in the solution there using `private Map<String, PlayerInventory> inventories` - maybe I'm misunderstanding you?

See this expanded solution:
```java
public Optional<PlayerInventory> getForWorld(Player player, World world)
{
	SomePlayer someplayer = SomePlayerColl.get().get(player.getUUID().toString());
	String worldId = world.getId();
	
	if (someplayer.getInventory(worldId).isPresent())
	{
		return Optional.of(someplayer.getInventory(worldId).get());
	}
	else 
	{
		return Optional.empty();
	}
}
```

**Comment by ulumulu1510** [comment]
Yes, @markehme was completely right.
You don't need to worry about inventory serialization, MassiveCore does that all for you.

Since I know now that you are heavily using MassiveCore, I'll give you my skype-Id (Id= titanusbenjaminus ). I am currently working on a beginners documentation for MassiveCore and it might help you too.

A senderColl gets populated automatically,  which is what you want in this case. Whenevery a player logs on, a new SenderEntity is instantiated in the SenderColl or fetched, in case there is already one in the system. The players uuid is the Id of the SenderEntity.

If you take a look at the MPlayer in Factions, you'll get a good idea of how it can be used.
Markehme delivered you a good example.

The three things you need to do to keep the DB up to date is:

- Load your fields in the load method
- call this.changed() after field assignment in a setter
- Put your Coll into the activate method of your main class.

Any of the above can be seen in MPlayerColl for Factions.

If you have any more question, please let me know over Skype :). I will see it sooner and thus be able to answer quicker over skype.

**Comment by MarkehMe** [comment]
See #295
