### ISSUE TITLE
Weird lag issue.

### ISSUE THREAD

**Issue by fanikz** [MassiveCraft/MassiveCore#298]
**Affected Plugin**

**Describe your environment**

* Affected Plugin version: 
* MassiveCore version: 
* Spigot version: 
* Config pastebin: 

**Steps to reproduce this bug**

  1. _____
  2. _____
  3. _____

**Observed results**

**Expected results**

https://timings.aikar.co/?id=b058462b81fb4cb4b17f8a9bb2d54537

**Comment by MarkehMe** [comment]
Please fill out the rest of your ticket.

You are missing:

* Affected Plugin version: 
* MassiveCore version: 
* Spigot version: 
* Config pastebin:

**Comment by ulumulu1510** [comment]
No information, timing report not available anymore.
