### ISSUE TITLE
Factions wont work

### ISSUE THREAD

**Issue by AnthonyWoolley** [MassiveCraft/MassiveCore#299]
* Affected Plugin version: Factions 2.8.10
* MassiveCore version: 2.8.10
* Spigot version: PaperSpigot( v1.11.2 20170218 )
**Observed results**
Console: https://pastebin.com/5R6ybBA6
when I do "/f" or "/factions", it send a message to me saying "Unknown command"

**Expected results**
This(or similler): https://s13.postimg.org/ime5kh57r/2017-04-18_17.37.31.png

**Comment by magnusulf** [comment]
It doesn't look like a full stack trace. Is it?

**Comment by Mytyit** [comment]
Update MassiveCore and Faction to 2.11 as is your PaperSpigot version.

**Comment by ulumulu1510** [comment]
This issue has been fixed locally and will be uploaded soon to spigot.
