### ISSUE TITLE
Chat message issue

### ISSUE THREAD

**Issue by Metisuneatn** [MassiveCraft/MassiveCore#300]
`[0;36;22m[[0;36;1m Prefix here [0;36;22m][0;37;1m[0;34;1m[[0;34;22m Suffix Here [0;34;1m][0;37;1m[0;34;22mJ[0;36;1mu[0;34;22ms[0;36;1mt[0;34;22mi[0;36;1mn[0;34;22mo[m[0;37;1m:[0;37;1m Chat Text Is Here[m
`

This happens to the logs sometimes on startup. It matches the startup messages from MassiveCore and does not always happen. 

1.11.2

**Comment by ulumulu1510** [comment]
You didn't use the appropriate format. This error doesn't appear on the newest version at all.
