### ISSUE TITLE
MassiveCore keeps coming up with this error in the console.

### ISSUE THREAD

**Issue by ZMeiza** [MassiveCraft/MassiveCore#301]
So MassiveCore keeps spamming this in my console, and I'm not sure what it means.
https://pastebin.com/WAsiXsSw

I would appreciate it if you could find a way around it

**Comment by MarkehMe** [comment]
Wow, weird!

Did your server crash recently or shut down incorrectly? Can you tell us a little bit of the history leading up to this?

From what I can see the database has corrupted, or something. 

Also, what are the versions of your plugins?

**Comment by ZMeiza** [comment]
We have had a couple of crashes before, but I'm pretty sure this is not the cause. Also all of my plugins normally tell me separately if they need to be updated with error messages, and the only plugin I am having slight problems with is is essentials, but that's different. What role does MassiveCore actually play on people's servers, with an Idea I could probably look in more depth

**Comment by MarkehMe** [comment]
Judging by your logs it has Factions. Factions uses MassiveCore. 

My concern is that on a crash the database may not have saved properly. Hence why its saying `"Database could not load entity. You edited a file manually and made wrong JSON?"`

Do you have a backup of the mstore folder you can roll back to?

**Comment by ZMeiza** [comment]
Im not sure, I do have a backup of the server. I could steal and replace the file from there? It isnt a very recent backup anyway

**Comment by MarkehMe** [comment]
It would mean there would be a loss of all data with MassiveCore based plugins (factions, etc) for that time period.

Is Factions functioning on your server?

**Comment by ZMeiza** [comment]
yes, but we have not made our server fully public yet. We only have a couple of test factions and players, so we would happily reset the data for Factions. Would it change the map we built our spawn in? Or..

**Comment by ZMeiza** [comment]
yes, but we have not made our server fully public yet. We only have a couple of test factions and players, so we would happily reset the data for Factions. Would it change the map we built our spawn in? Or..

**Comment by oloflarsson** [comment]
Please remove the empty files in question. If new files keep appearing it's probably you have run out of disk space?
