### ISSUE TITLE
Error occurred while enabling MassiveCore (org/bukkit/scoreboard/Team$Option)

### ISSUE THREAD

**Issue by DardBrinza** [MassiveCraft/MassiveCore#304]
MassiveCore version: 2.11.0
Spigot version: latest paper 1.8.8
Config: default

Error on start: https://pastebin.com/AJrYDUD4

**Comment by Diamondman121314** [comment]
I have the same exact error with basically everything DardBrinza said.

**Comment by DardBrinza** [comment]
@MarkehMe bump

**Comment by Twonox** [comment]
Same issue

**Comment by Diamondman121314** [comment]
Same issue with 2.12.0.

**Comment by oloflarsson** [comment]
Thank you for this bug report. We have been bussy with exams and work. The next version solves this issue.
