### ISSUE TITLE
1.12 Update Causes MassiveCore to Crash

### ISSUE THREAD

**Issue by NerdyPacman** [MassiveCraft/MassiveCore#306]
MassiveCore and Factions

**Describe your environment**

* Affected Plugin version: 2.12.0
* MassiveCore version: 2.12.0
* Spigot version: 1.12
* Config pastebin: https://pastebin.com/uUYb3dkw

**Steps to reproduce this bug**

  1. Install Spigot 1.12.
  2. Add MassiveCore.jar to plugins.
  3. Read console.

**Observed results**

I created a new server to troubleshoot Factions. I start up Spigot, and it shows error messages with MassiveCore in them. I then deleted Factions so I know the error is from MassiveCore. Also, when Factions was installed, both plugins would show in /plugins as green. However, I could use no commands from them. No /f, nothing. So I came here for help.

server log on Pastebin: https://pastebin.com/zFhggmz6

No images needed, also the mstore folder is empty.

**Expected results**

I expect there to be /f, and for there to not be errors. This all happened when I updated.

**Comment by Dart2112** [comment]
"[22:39:20 ERROR]: Could not load 'plugins\Factions.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: MassiveCore
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot.jar:git-Spigot-8cbfc85-ec47e79]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot.jar:git-Spigot-8cbfc85-ec47e79]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-8cbfc85-ec47e79]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-8cbfc85-ec47e79]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]"
that error is because you dont have Massive Core installed... the server doesnt even mention massive core

**Comment by magnusulf** [comment]
The console says neither plugin is loaded. So if they show up when doing /plugins something is really weird. Unless MassiveCore is not even in your plugins folder I have no clue on what is going on.

**Comment by nexlemav** [comment]
I have had the same issue. No commands run.  /pl plugin shows all plugins in green but nothing works

**Comment by NerdyPacman** [comment]
They are both in the folder.

**Comment by oloflarsson** [comment]
You need to have both MassiveCore and Factions in the plugins folder. This message appears when you have just Factions and not MassiveCore. Please double check that you actually have both plugin jars in the plugins folder.

**Comment by oloflarsson** [comment]
Thank you for the bug report. I hope you managed to fix this by installing the same version of Factions and MassiveCore.
