### ISSUE TITLE
Supress Mixin Console Logging

### ISSUE THREAD

**Issue by kmecpp** [MassiveCraft/MassiveCore#314]
MassiveCore: 2.13.0
Spigot: 1.11.2

Currently there's a lot of console output with MassiveCore on startup. Can't some of the logging (specifically the Mixin stuff) be moved to the debug stream? Or can there be a config to disable the Mixin logging? I don't really think this is useful to enough people to display on every single startup.

Screenshot:
![image](https://user-images.githubusercontent.com/6520738/27974007-1bfdc9f6-632a-11e7-86a7-18ff43f4224c.png)

**Comment by oloflarsson** [comment]
I agree, this is a good suggestion.

**Comment by oloflarsson** [comment]
Fixed in https://github.com/MassiveCraft/MassiveCore/commit/cf446663d073ec96b24f963e1d9bd0248c0537e0
