### ISSUE TITLE
New Feature. Not Connected terrain

### ISSUE THREAD

**Issue by jakovkacan** [MassiveCraft/MassiveCore#316]
Factions

* Affected Plugin version:  2.8.20
* MassiveCore version: 2.8.20
* Spigot version: 1.11
* Config pastebin: Not importatnt

If it is possible I would like to request a feature. It would be nice to enable "claiming terrain not attached to another terrain" (You can claim terrain that is not connected to first claimed terrain)

It would be cool to make that option tickable in config.

**Comment by ulumulu1510** [comment]
Please make your report on the correct repository and all the wanted information on the form.
