### ISSUE TITLE
MassiveCore couldn't be enabled.

### ISSUE THREAD

**Issue by zombieknifer223** [MassiveCraft/MassiveCore#317]
**Affected Plugin**
MassiveCore

**Describe your environment**

* MassiveCore version: 2.11.0
* Spigot version: Paper 1.8.8 (Final)
* Config Pastebin: https://pastebin.com/YgS1EUQH
* Console Log Pastebin: https://pastebin.com/vWsGMMXu

**Steps to reproduce this bug**

Start the latest version of MassiveCore on Paper 1.8.8 (Final)

**Observed results**

I noticed the error when Factions wasn't being enabled. I knew it was MassiveCore cause Factions couldn't work at all with it.

**Expected results**

I expected MassiveCore to be enabled thus letting Factions work as well.

**Comment by ulumulu1510** [comment]
Update your version of MassiveCore and Factions, this bug has already been fixed.
