### ISSUE TITLE
MassiveCore Error 1.12.2

### ISSUE THREAD

**Issue by KorkugunuB** [MassiveCraft/MassiveCore#339]
## Affected Plugin
- **Affected Plugin Name:** MassiveCore
- **Affected Plugin Version:** 2.13.6
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 2.13.6

## Describe your Environment
- **Server Version:** CraftBukkit version git-Spigot-4bd94dc-bacaf92 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

## Steps to Reproduce this Bug

1. I installed MassiveCore.
2. Then I installed Factions, turned on the server.
3. The plugin wasn't loading.

## Observed Results
MassiveCraft is enabling itself and disabling upon startup
MassiveCraft error : https://prnt.sc/igbei3 
Factions error : https://prnt.sc/igbeod

**Comment by OnwexryS** [comment]
I have the same problem what should we do ?

**Comment by OnwexryS** [comment]
What should we do to go on ?
