### ISSUE TITLE
Plugin not enabling.

### ISSUE THREAD

**Issue by heyimnox** [MassiveCraft/MassiveCore#342]
## Affected Plugin
- **Affected Plugin Name:** MassiveCore
- **Affected Plugin Version:** 2.13.6

## Describe your Environment
- **Server Version:** PaperSpigot [git-Paper-1335 (MC 1.12.2)]

## Steps to Reproduce this Bug
1. Left the server running
2. MassiveCore and Factions randomly stopped working

## Observed Results
MassiveCore and Factions are not being enabled.
https://pastebin.com/Pa2My0vm

## Expected Results
I expected the plugin to run like it was before. Can't really say much else.

**Comment by TheComputerGeek2** [comment]
@heyimnox is this still an issue? If so, could you include the error from MassiveCore? I think that will be slightly more useful for determining what happened.

**Comment by heyimnox** [comment]
It's no longer an issue; I suspect it may have been caused by the backup system my host provided. Snapshots were taken every 12 hours, which may have messed with some config file somewhere. I was able to fix the issue by uninstalling everything and reinstalling everything, saving all the configs, world files, and plugins I knew were still working.
